# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footagedetail',
            name='city',
        ),
        migrations.AddField(
            model_name='footagedetail',
            name='city',
            field=models.CharField(choices=[('Białystok', 'Białystok'), ('Bydgoszcz', 'Bydgoszcz'), ('Częstochowa', 'Częstochowa'), ('Gdynia', 'Gdynia'), ('Gdańsk', 'Gdańsk'), ('Łódź', 'Łódź'), ('Katowice', 'Katowice'), ('Kraków', 'Kraków'), ('Lublin', 'Lublin'), ('Opole', 'Opole'), ('Poznań', 'Poznań'), ('Radom', 'Radom'), ('Sosnowiec', 'Sosnowiec'), ('Szczecin', 'Szczecin'), ('Toruń', 'Toruń'), ('Warszawa', 'Warszawa'), ('Wrocław', 'Wrocław')], default=0, max_length=64),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
