# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footage', '0002_auto_20171004_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='footage',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
